import { BALANCE } from "./balance.js";

export const ENEMY_TYPES = {
  basico: {
    key: "basico",
    name: "Básico",
    hp: 40,
    speed: 1.1,
    reward: 12,
    color: "#ffd166",
    radius: 11,
    armor: 0,
    flying: false,
    onDeath: null,
  },
  rapido: {
    key: "rapido",
    name: "Rápido",
    hp: 22,
    speed: 2.1,
    reward: 14,
    color: "#06d6a0",
    radius: 9,
    armor: 0,
    flying: false,
    onDeath: null,
  },
  tanque: {
    key: "tanque",
    name: "Tanque",
    hp: 140,
    speed: 0.6,
    reward: 30,
    color: "#b5179e",
    radius: 15,
    armor: 0.15,
    flying: false,
    onDeath: null,
  },
  volador: {
    key: "volador",
    name: "Volador",
    hp: 55,
    speed: 1.5,
    reward: 18,
    color: "#90e0ef",
    radius: 10,
    armor: 0,
    flying: true,
    onDeath: null,
  },
  blindado: {
    key: "blindado",
    name: "Blindado",
    hp: 90,
    speed: 0.9,
    reward: 24,
    color: "#8d99ae",
    radius: 13,
    armor: 0.45,
    flying: false,
    onDeath: null,
  },
  divisor: {
    key: "divisor",
    name: "Divisor",
    hp: 70,
    speed: 1.0,
    reward: 16,
    color: "#f15bb5",
    radius: 13,
    armor: 0,
    flying: false,
    onDeath: "split",
  },
  jefe: {
    key: "jefe",
    name: "Jefe",
    hp: 1200,
    speed: 0.45,
    reward: 250,
    color: "#ff006e",
    radius: 22,
    armor: 0.3,
    flying: false,
    onDeath: null,
    boss: true,
  },
};

export const MAX_HP_SCALE = BALANCE.enemyHpScalePerWave;
