export function createState(map) {
  return {
    map,
    pathPoints: map.pathPoints,
    blocked: map.blocked,
    base: map.base,
    vida: map.startLife,
    vidaMax: map.startLife,
    oro: map.startGold,
    oleada: 0,
    totalOleadas: 0,
    torres: [],
    enemigos: [],
    proyectiles: [],
    floaters: [],
    selectedTower: 0,
    selectedTowerEntity: null,
    oleadaActiva: false,
    spawnQueue: [],
    spawnTimer: 0,
    gameOver: false,
    victory: false,
    hoverCell: null,
    flash: { msg: "", timer: 0 },
    weather: { type: "clear", t: 0 },
    abilityCd: {},
    baseShield: 0,
    stats: {
      kills: 0,
      bosses: 0,
      elites: 0,
      dmgDealt: 0,
      goldEarned: 0,
      goldSpent: 0,
      maxOro: 0,
      towersByType: {},
    },
  };
}
